[package]
name = "typed_format"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
pest = "2.1.3"
serde = "1.0.115"
base64 = "0.12.3"
anyhow = "1.0.32"

[dev-dependencies]
serde_derive = "1.0.115"
maplit = "1.0.2"
